### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by Pus12** [imvast/Discord-MassDM#10]
i am cded into C:\Users\User\Discord-MassDM-main but when i do pip install -r requirements.txt cmd says ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' can anyone help

**Comment by imvast** [comment]
shutup retard

**Comment by Ghostlogss** [comment]
💀
