### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by immrb** [imvast/Discord-MassDM#5]
ImportError: cannot import name 'Solver' from 'veilcord' (C:\Users\immrb\AppData\Roaming\Python\Python311\site-packages\veilcord\__init__.py)

**Comment by ux6** [comment]
I'm also getting this

**Comment by alluding** [comment]
> ImportError: cannot import name 'Solver' from 'veilcord' (C:\Users\immrb\AppData\Roaming\Python\Python311\site-packages\veilcord__init__.py)

Because Vastien is a little slow in understanding and made a mistake with his library, deleting the `Solver` class, now it's broken. He has to fix it, which he won't because hes retarded.

**Comment by imvast** [comment]
bruh
