### ISSUE TITLE
where is requirements.txt?

### ISSUE THREAD

**Issue by khovansky007** [imvast/Discord-MassDM#7]

**Comment by khovansky007** [comment]
aiohttp==3.9.3
aiosignal==1.3.1
anyio==4.3.0
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
colorama==0.4.6
discord.py==2.3.2
frozenlist==1.4.1
google-re2==1.1
h11==0.14.0
httpcore==1.0.4
httpx==0.27.0
idna==3.6
multidict==6.0.5
requests==2.31.0
sniffio==1.3.1
terminut==0.0.0.940
tls-client==1.0.1
typing_extensions==4.10.0
urllib3==2.2.1
veilcord==0.0.7.4
websocket-client==1.7.0
yarl==1.9.4

**Comment by imvast** [comment]
💀
