### ISSUE TITLE
Method "get" is not defined.

### ISSUE THREAD

**Issue by khovansky007** [imvast/Discord-MassDM#8]
File "C:\Users\Luntyara\Desktop\Discord-MassDM-main\main.py", line 244, in start
    guild_id = Joiner(token, invite).JoinServer().get("id")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by imvast** [comment]
idrc
